name: Github action for auto assigning devs to pull requests

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - 'dev-*'

jobs:
  set_assignee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: test-id
        with:
          script: |
            console.log(context.actor)
            console.log(context.repo.owner)
            console.log(context.repo.repo)
            console.log(context.issue.number)
            console.log(context.payload.number)
            console.log('--------------------------------------------------------')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })


          # github.rest.issues.addAssignees({
            # owner: context.repo.owner,
            # repo: context.repo.repo,
            # issue_number: github.event.number,
            # assignees: [context.actor],
          # })