name: Github action for auto assigning devs to pull requests

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  set_assignee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: test-id
        with:
          script: |
            console.log(context.actor)
            console.log(context.repo.owner)
            console.log(context.repo.repo)
            console.log(context.issue.number)
            console.log(context.payload.number)
            console.log(context)
            console.log('---------------------------------------------------------')

          # github.rest.issues.createComment({
            #   owner: context.repo.owner,
            #   repo: context.repo.repo,
            #   issue_number: context.issue.number,
            #   body: '👋 Thanks for reporting!'
            # })
            # github.rest.issues.addLabels({
            #   issue_number: 1,
            #   owner: context.repo.owner,
            #   repo: context.repo.repo,
            #   labels: ['Triage1']
            # })
            
          # github.rest.issues.addAssignees({
            # owner: context.repo.owner,
            # repo: context.repo.repo,
            # issue_number: github.event.number,
            # assignees: [context.actor],
          # })